### ISSUE TITLE
Ausgabe Metadaten

### ISSUE THREAD

**Issue by Luminanz** [Craffft/contao-photoalbums2#115]
Hallo 

Gibt es eine Möglichkeit, die Metadaten aus der Dateiverwaltung (Titel und Bildunterschrift) auszugeben?

Danke für die Rückmeldung.

**Comment by Luminanz** [comment]
Habe nun gesehen, dass zumindest der Titel (falls in der korrekten Sprache vorhanden) ausgegeben wird (überschreibt den Dateinamen im title). Es wäre praktisch, wenn die Bildunterschrift ebenfalls im Frontendtemplate verfügbar wäre.
Daher wohl eher ein Feature-Request

**Comment by iCodr8** [comment]
Ist nun im pa2_image template verfügbar.
