### ISSUE TITLE
check permission

### ISSUE THREAD

**Issue by Luminanz** [Craffft/contao-photoalbums2#117]
Ein Redaktuer kann ein neues Album nur an der obersten Stelle einfügen, ansonsten tritt ein Fehler auf. Eventell kann man auf das Ermitteln der String-Länge verzichten, denn ohne diese würde es funtkionieren. 

case 'create':
if (!strlen($this->Input->get('pid')) || !in_array($this->Input->get('pid'), $root)) {

**Comment by iCodr8** [comment]
Ja, ich denke schon. Ich werde es prüfen und ggfs. umsetzen.

**Comment by iCodr8** [comment]
Das Problem ist wahrscheinlich nicht der check, sondern, dass keine PID übergeben wird. Das muss ich genauer analysieren.

**Comment by iCodr8** [comment]
War nicht ganz so einfach. Aber sollte nun funktionieren.
