### ISSUE TITLE
Extension not installable via Composer

### ISSUE THREAD

**Issue by fritzmg** [Craffft/contao-photoalbums2#119]
Currently this extension is not installable via composer. The information on packagist still references the old repositories - instead of `craffft/contao-photoalbums2` you still have to use [icodr8/contao-photoalbums2](https://packagist.org/packages/icodr8/contao-photoalbums2). But even if you do, the installation via composer will fail, because the requirements cannot be satisfied, since there is no `craffft/contao-imagesortwizard` package for example. Composer output:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - icodr8/contao-photoalbums2 dev-master requires craffft/contao-imagesortwizard ~2.2 -> no matching package found.
    - icodr8/contao-photoalbums2 1.5.0 requires craffft/contao-imagesortwizard ~2.2 -> no matching package found.
    - Installation request for icodr8/contao-photoalbums2 >=1.5.0.0 -> satisfiable by icodr8/contao-photoalbums2[1.5.0, dev-master].
```

**Comment by iCodr8** [comment]
Sorry, I forgot to add all the __icodr8__ repositories to the new __craffft__ namespace. They are now available and composer works like before :)

**Comment by fritzmg** [comment]
thx :)
