### ISSUE TITLE
Warning: Ambiguous class resolution

### ISSUE THREAD

**Issue by fritzmg** [Craffft/contao-photoalbums2#120]
When this extension is installed via composer, there is a small issue. Whenever a composer update is run, the composer issues this warning:

```
Warning: Ambiguous class resolution, "Photoalbums2\Photoalbums2Runonce" was found in both "composer\vendor\icodr8\contao-photoalbums2\system\modules\photoalbums2\config\runonce.php" and "composer\vendor\icodr8\contao-photoalbums2\system\modules\photoalbums2\config\_runonce.php", the first will be used.
```

This is due to the presence of the `runonce.php` and the `_runonce.php`. I am assuming the latter is just there for developing purposes to keep a copy of the runonce.php, since it gets deleted automatically by Contao.

**Comment by iCodr8** [comment]
Hab die _runonce.php entfernt. Diese war eigentlich nur zur Entwicklung gedacht und hätte nicht in das Projekt gelangen sollen.
