### ISSUE TITLE
Fehler in classes/Pa2ImageViewParser.php

### ISSUE THREAD

**Issue by Seefahrer** [Craffft/contao-photoalbums2#121]
Bei Ausführung des Scripts kommt es zur Fehlermeldung:
Fatal error: Call to a member function row() on null in ... cms/system/modules/photoalbums2/classes/Pa2ImageViewParser.php on line 334

Habe jetzt versuchsweise die Zeilen 334/335 auskommentiert. Damit funktioniert die Einzelansicht der Bilder zwar wieder, aber ich weiss nicht welche Seiteneffekte auftreten können.

Fehler tritt in Contao 3.4.5 und 3.5 RC1 auf ...

**Comment by iCodr8** [comment]
Ich konnte den Fehler nicht nachstellen, habe aber mal einen check eingebaut, der in dem Fall die Fehlermeldung abfängt und den Back Button dann nicht anzeigt.
