### ISSUE TITLE
FR: Vorschaubild = 1. Bild

### ISSUE THREAD

**Issue by mathContao** [Craffft/contao-photoalbums2#123]
im alten Photoalbums wurde automatisch das erste Bild als Vorschau-Bild genutzt, wenn nicht anders eingestellt.

Wäre aus meiner Sicht eine sehr hilfreiche Erweiterung zu "kein Vorschaubild" (wobei mir diese Einstellung keinen Sinn ergibt), "zufälliges Vorschaubild" (widerspricht aus meiner Sicht ein wenig dem Deckblatt = Erkennungscharakter (bei mehreren Alben verwirrend, wenn sich alle Vorschaubilder bei jedem Seitenaufruf ändern) und erzeugt zusätzlich PHP-Last durch das Random.) und "Vorschaubild auswählen" (Zusätzlicher Klickaufwand, häufig ist es das erste Bild)

**Comment by iCodr8** [comment]
Erstes Bild wird default. Die anderen Optionen bleiben drin.
