### ISSUE TITLE
FR: Albenauflistung mit mehr Infos

### ISSUE THREAD

**Issue by mathContao** [Craffft/contao-photoalbums2#124]
FR (Feature Request):
Ich vermisse die Übersichtlichkeit der Fotoalben in der Auflistung aus dem alten Photoalbums:

Photoalbums2
![bild1](https://cloud.githubusercontent.com/assets/1645099/9068913/88e9e554-3ae6-11e5-973f-60fe0eb4be70.png)

Photoalbums (alt)
![bild2](https://cloud.githubusercontent.com/assets/1645099/9068993/22b2d998-3ae7-11e5-8815-c5cbb8b14ff2.png)

Für mich ist es sehr hilfreich in der Übersicht zu sehen: Name des Albums (ist in Photoalbums vorhanden) und zusätzlich: Datum, Ereignis, Fotograf, Ort.

**Comment by iCodr8** [comment]
Das Problem dabei ist, dass es sehr viel Performance zieht, sobald ein paar mehr Alben vorhanden sind.  Das ist auch der Grund, weshalb das aktuell so gelöst ist.
