### ISSUE TITLE
Beschreibung: kein leerer Content möglich

### ISSUE THREAD

**Issue by mathContao** [Craffft/contao-photoalbums2#125]
Legt man ein neues Album an, dann befinden sich im Text "Beschreibung" folgende Elemente im Editor. Bekomm ich auch nicht weg.

![unbenannt](https://cloud.githubusercontent.com/assets/1645099/9069209/38287d86-3ae8-11e5-99f8-96456fb72757.JPG)

Contao 3.5.2, Photoalbums 1.5, translation_fields   1.4.0

**Comment by iCodr8** [comment]
Bitte Photoalbums 1.5.1 und Translation Fields auf 1.6.0 upgraden.
