### ISSUE TITLE
CSS: auf margin-Angaben verzichten

### ISSUE THREAD

**Issue by mathContao** [Craffft/contao-photoalbums2#126]
photoalbums2.css (Zeile 9 ff):

```
.mod_photoalbums2 .albumswrap .album .albumInside,
.mod_photoalbums2 .imagewrap .image .imageInside,
.ce_photoalbums2 .albumswrap .album .albumInside,
.ce_photoalbums2 .imagewrap .image .imageInside{margin-left: 10px; margin-right: 10px; overflow: hidden;}
.mod_photoalbums2 .albumswrap .album.first .albumInside,
.mod_photoalbums2 .imagewrap .image.first .imageInside,
.ce_photoalbums2 .albumswrap .album.first .albumInside,
.ce_photoalbums2 .imagewrap .image.first .imageInside{margin-left: 0px;}
.mod_photoalbums2 .albumswrap .album.last .albumInside,
.mod_photoalbums2 .imagewrap .image.last .imageInside,
.ce_photoalbums2 .albumswrap .album.last .albumInside,
.ce_photoalbums2 .imagewrap .image.last .imageInside{margin-right: 0px;}
```

Diese Margin-Angaben sind in der Albenübersicht im Frontend-Template hinderlich bzw. führen zu einen inkorrekten/unschönen Ergebnis, wenn .albumInside eine Hintergrundfarbe erhält und z.B. 3 Alben in einer Zeile angezeigt werden sollen. Dann ist die mittlere Spalte schmaler als links und rechts.

Da es sich bei den oben genannten margins nur um gestalterische Feinheiten handelt, würde im empfehlen die margins aus dem CSS zu entfernen und ggf. dem Designer der Webseite überlassen ein individuelles Layout zu erstellen

**Comment by iCodr8** [comment]
Wir haben es so optimiert, dass die Abstände weiterhin existieren. Jedoch eine Ebene höher und nicht mit margin, sondern mit padding. Somit kann in der bisherigen Ebene der Hintergrund gefärbt werden. In besonderen Fällen muss der jeweilige Entwickler eben die CSS-Regeln überschreiben.
