### ISSUE TITLE
release for Contao > 3.2?

### ISSUE THREAD

**Issue by fritzmg** [Craffft/contao-photoalbums2#128]
Currently the extension is only available up to Contao 3.3.7 in the ER2 and via Composer even only up to Contao 3.2.21 due to the restrictive `contao/core` requirement of `>=3.2,<3.3-dev`. Will there ever be a Release for Contao 3.5?

**Comment by denniserdmann** [comment]
+1
I'm also interested in a Version for Contao 3.5 (upgrading [translation-fields] makes photoalbums2 unusable)

**Comment by iCodr8** [comment]
Yes it will be, but currently there is not time.

**Comment by iCodr8** [comment]
Support for Contao 3.5+ is implemented with 1.5.2. Older versions won't be supported anymore.
