### ISSUE TITLE
PHP Recoverable error in Contao 3.5.6

### ISSUE THREAD

**Issue by Samson1964** [Craffft/contao-photoalbums2#131]
Siehe dazu meine Meldung im [Contao-Forum](https://community.contao.org/de/showthread.php?61294-Photoalbums2-PHP-Recoverable-error)

**Comment by iCodr8** [comment]
Fehler kann mit der aktuellen Version 1.5.1 und Translation Fields 1.6.0 nicht nachgestellt werden.
