### ISSUE TITLE
assets/blank.gif is not a valid GIF file

### ISSUE THREAD

**Issue by Samson1964** [Craffft/contao-photoalbums2#134]
Nachfolgende Meldungen stehen zuhauf in meinem error.log:
```
PHP Warning: imagecreatefromgif(): 'system/modules/photoalbums2/assets/blank.gif'
is not a valid GIF file in /xxx/vendor/tecnickcom/tcpdf/tcpdf.php on line 7033
```
blank.gif vom 16.07.2013 ist 37 Byte groß. 
Ich habe die Datei mit PSP bei mir mal neu gespeichert.

**Comment by iCodr8** [comment]
Die Frage ist, was hat das GIF in tcpdf verloren?

**Comment by iCodr8** [comment]
Hab einfach ein neues erstellt und ausgetauscht.
