### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by Luminanz** [Craffft/contao-photoalbums2#135]
I use Version 1.6.0 with contao 3.5.30 and I always get the following error when I try to edit an album:

Fotos sortieren

Fatal error: Cannot use 'String' as class name as it is reserved in /home/fotogra2/public_html/foto-art/system/modules/core/library/Contao/String.php on line 28

(this error occurs only when using PHP 7)

**Comment by BugBuster1701** [comment]
Look here: https://github.com/Craffft/contao-imagesortwizard/issues/3#issuecomment-339352214

**Comment by iCodr8** [comment]
Already done with a newer version of https://github.com/Craffft/contao-imagesortwizard/releases/tag/2.3.1
