### ISSUE TITLE
wrong Contao minimum requirement

### ISSUE THREAD

**Issue by fritzmg** [Craffft/contao-photoalbums2#136]
The usage of the `Contao\StringUtil` class was introduced in 5695d0ea24089d598aa91c0bfce9500952838490. However, this class is only present in Contao `>=3.5.1` - yet the `composer.json` still has`^3.2 || ^4.2` as the minimum requirement for version 1.6.x.

This will lead to a
```
 Class 'Contao\StringUtil' not found
```
in earlier Contao versions after a composer update.

**Comment by fritzmg** [comment]
For anyone encountering this in one of their old Contao installations, you can add
```
    "conflict": {
        "icodr8/contao-photoalbums2": "1.6.0",
        "craffft/contao-imagesortwizard": "2.3.1"
    },
```
to your `composer.json` and then run an update again.

(See also https://github.com/Craffft/contao-imagesortwizard/issues/4)

**Comment by iCodr8** [comment]
Can you fix it in a pull request?

**Comment by iCodr8** [comment]
I think that problem exists only in Contao 3, so it will not be fixed.
