### ISSUE TITLE
Cannot find editor configuration file "tinyFlash.php"

### ISSUE THREAD

**Issue by Sizoberz** [Craffft/contao-photoalbums2#137]
I can create a archive but no gallery - then I get this message.
This message also appears when I want to add the gallery module.

**Comment by Samson1964** [comment]
Workaround bis das offiziell gefixed wird: Kopiere /system/config/tinyFlash.php aus der 3er Installation in das Verzeichnis /app/Resources/contao/config/. Ggfs. mußt Du das Zielverzeichnis erst anlegen.
Danach bearbeitest Du die Datei /vendor/craffft/contao-translation-fields/system/modules/translation-fields/widgets/TranslationTextArea.php und dort die Zeilen wo "/system/config/" steht. Bei mir sind das die Zeilen 156 und 169. Dort schreibst Du stattdessen "/app/Resources/contao/config/" hin. Damit ist die Datei C4-kompatibel. Also fast. Eigentlich gibt es ja tinyFlash.php u.ä. in C4 nicht mehr.

**Comment by iCodr8** [comment]
Wie läuft das inzwischen bei Contao mit der TinyMCE Konfiguration? Gibt es das Template an einem anderen Ort?

**Comment by iCodr8** [comment]
Das Problem wurde im translation-fields-bundle gelöst. In Photoalbums2 wird allerdings noch das veraltete contao-translation-fields genutzt. Somit wird das Problem in Photoalbums2 erst gelöst, wenn auf das neue translation-fields-bundle umgestellt wurde.

https://github.com/Craffft/translation-fields-bundle/commit/8d6c4e90109fe97272d67d1c493922369e867762

**Comment by CK2407** [comment]
Hallo,

Ich bin heute auch mit einer 4.7.2 Version von Contao auf das Problem gestoßen.
Die Lösung von Samson1964 scheint nicht mehr zu funktionieren, zumindest bei mir nicht.

Allerdings habe ich als Alternative in der Datei /vendor/craffft/contao-photoalbums2/system/modules/photoalbums2/dca|tl_photoalbums2_album.php (bei mir in Zeile 244) das Array , in dem tinyFlash als rte eingetragen ist, leer gelassen.

vorher:
'eval'                    => array('rte' => 'tinyFlash')

nachher:
'eval'                    => array()

Das Album funktioniert nun, allerdings wird jetzt bei der Beschreibung kein Richtexteditor mehr genutzt, sondern eine normale Textarea.

**Comment by iCodr8** [comment]
Done in `2.1.0`
