### ISSUE TITLE
Photoalbums2 no longer working in Contao 4.5.0

### ISSUE THREAD

**Issue by Seefahrer** [Craffft/contao-photoalbums2#138]
After update of Contao from 4.4.11 to 4.5.0, PA2 is no longer working but throws
"Internal Server Error"

No entry in the logfile ...

**Comment by spunktonline** [comment]
PA2 tries to load tinyFlash which is not longer available in Contao 4.5.3, so it isn't possible to create photo albums...

**Comment by k-webdesign** [comment]
Will this be fixed soon?

**Comment by iCodr8** [comment]
Yes, in the next 2 weeks.

**Comment by iCodr8** [comment]
Done in `2.1.0`
