### ISSUE TITLE
Eingabefelder werden überlagert

### ISSUE THREAD

**Issue by Samson1964** [Craffft/contao-photoalbums2#139]
Im DCA werden unter Contao 4 Eingabefelder überlagert und sind nicht editierbar. Aufgefallen ist mir das bei "Ereignis" und "Aufnahmeort". Weitere Informationen unter https://community.contao.org/de/showthread.php?69208-Einige-Input-Felder-im-BE-lassen-sich-nicht-bearbeiten

**Comment by iCodr8** [comment]
Done in `2.1.0`
