### ISSUE TITLE
Alben-Sortierung im Frontendmodul

### ISSUE THREAD

**Issue by yeli69** [Craffft/contao-photoalbums2#98]
Die Sortierung der Alben im Frontend sollte zusätzlich wie die manuelle Sortierung im Backend funktionieren.
Außerdem wäre es sehr nützlich, wenn man die Liste der Fotoalben gruppiert nach den Archiven ausgeben könnte. Die Sortierung der Alben müsste dann natürlich pro Archiv stattfinden.

**Comment by Luminanz** [comment]
Aus meiner Sicht wäre die Sortierung der Alben im Frontend wie die manuelle Sortierung im Backend sehr hilfreich aus folgendem Grund:
Redakteure haben normalerweise keinen Zugriff auf die Einstellungen des Frontend-Moduls und daher wäre es sinnvoll wenn die Sortierung der Alben im backend auch im frontend übernommen würde, zumal ja die Alben einfach sortiert/verschoben werden können, sonst macht diese Funktion ja keinen grossen Sinn.

**Comment by Luminanz** [comment]
Aus meiner Sicht müsste die Code-Ergänzung in Pa2AlbumSorter eher so aussehen:

                    case 'sorting':
                        $sortType = SORT_NUMERIC;
                        $sorting = '';

                        if ($objPa2AlbumModel->sorting != '') {
                            $sorting = $objPa2AlbumModel->sorting;
                        }

                        $arrSort[$objPa2AlbumModel->id] = $sorting;
                        break;

**Comment by iCodr8** [comment]
Wir von Craffft werden dieses Feature nicht implementieren, da wir schon alleine für den Support von Photoalbums wenig Zeit haben. Pull Requests sind von der Community gerne willkommen.
